<a href="https://colab.research.google.com/github/CamusMak/PyTorchFundamentals/blob/main/Copy_of_pytorch_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("GPU run time")

GPU run time


In [2]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [3]:
import pandas as pd
import numpy as np
import torch
import matplotlib.pyplot as plt

print(torch.__version__)


1.13.1+cu116


## Introduction to Tensors

### Creating tensors

In [4]:
# scalar

scalar = torch.tensor(77)
print(scalar.dtype)
print(type(scalar))
scalar


torch.int64
<class 'torch.Tensor'>


tensor(77)

In [5]:
scalar.ndim

0

In [6]:
scalar.shape

torch.Size([])

In [7]:
# like in numpy item() method get value from tensor/array
scalar.item()

77

In [8]:
# vector
vector = torch.tensor([7,7])
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
MATRIX = torch.tensor([[1,2,3],
                       [4,5,6]])

In [11]:
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
MATRIX.shape

torch.Size([2, 3])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX[:,1]

tensor([2, 5])

In [15]:
MATRIX.size()

torch.Size([2, 3])

In [16]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5]],
                       [[7,8,9],
                        [10,11,12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  4,  5]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [17]:
TENSOR.size()

torch.Size([2, 2, 3])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5]])

In [20]:
TENSOR[1]

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [21]:
TENSOR[0][0][0]

tensor(1)

### RANDOM TENSORS